Process: pl.prabel.githubdemo.debug, PID: 23756
rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
    at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:201)
    at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:111)
    at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
    at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
    at rx.internal.operators.OperatorFilter$1.onError(OperatorFilter.java:47)
    at rx.internal.operators.OperatorMap$1.onError(OperatorMap.java:49)
    at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:58)
    at com.jakewharton.rxbinding.view.ViewClickOnSubscribe$1.onClick(ViewClickOnSubscribe.java:23)
    at android.view.View.performClick(View.java:6294)
    at android.view.View$PerformClick.run(View.java:24770)
    at android.os.Handler.handleCallback(Handler.java:790)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6494)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
 Caused by: rx.exceptions.CompositeException: 3 exceptions occurred.
    at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:201) 
    at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:111) 
    at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70) 
    at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70) 
    at rx.internal.operators.OperatorFilter$1.onError(OperatorFilter.java:47) 
    at rx.internal.operators.OperatorMap$1.onError(OperatorMap.java:49) 
    at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:58) 
    at com.jakewharton.rxbinding.view.ViewClickOnSubscribe$1.onClick(ViewClickOnSubscribe.java:23) 
    at android.view.View.performClick(View.java:6294) 
    at android.view.View$PerformClick.run(View.java:24770) 
    at android.os.Handler.handleCallback(Handler.java:790) 
    at android.os.Handler.dispatchMessage(Handler.java:99) 
    at android.os.Looper.loop(Looper.java:164) 
    at android.app.ActivityThread.main(ActivityThread.java:6494) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
 Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
    at android.util.Log.printlns(Log.java:419)
    at com.android.internal.os.RuntimeInit.Clog_e(RuntimeInit.java:61)
    at com.android.internal.os.RuntimeInit.-wrap0(Unknown Source:0)
    at com.android.internal.os.RuntimeInit$LoggingHandler.uncaughtException(RuntimeInit.java:90)
    at java.lang.Thread.dispatchUncaughtException(Thread.java:1950)
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.text.Editable android.widget.EditText.getText()' on a null object reference
    at pl.prabel.githubdemo.presenter.login.LoginActivity$MapToUsernameWithPasswordFunc.call(LoginActivity.java:116)
    at pl.prabel.githubdemo.presenter.login.LoginActivity$MapToUsernameWithPasswordFunc.call(LoginActivity.java:111)
    at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
    at com.jakewharton.rxbinding.view.ViewClickOnSubscribe$1.onClick(ViewClickOnSubscribe.java:23)
    at android.view.View.performClick(View.java:6294)
    at android.view.View$PerformClick.run(View.java:24770)
    at android.os.Handler.handleCallback(Handler.java:790)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6494)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
 Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: null
    at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:58)
    at com.jakewharton.rxbinding.view.ViewClickOnSubscribe$1.onClick(ViewClickOnSubscribe.java:23) 
    at android.view.View.performClick(View.java:6294) 
    at android.view.View$PerformClick.run(View.java:24770) 
    at android.os.Handler.handleCallback(Handler.java:790) 
    at android.os.Handler.dispatchMessage(Handler.java:99) 
    at android.os.Looper.loop(Looper.java:164) 
    at android.app.ActivityThread.main(ActivityThread.java:6494) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
 Caused by: java.lang.RuntimeException: Duplicate found in causal chain so cropping to prevent loop ...
    at android.util.Log.printlns(Log.java:419)
    at com.android.internal.os.RuntimeInit.Clog_e(RuntimeInit.java:61)
    at com.android.internal.os.RuntimeInit.-wrap0(Unknown Source:0)
    at com.android.internal.os.RuntimeInit$LoggingHandler.uncaughtException(RuntimeInit.java:90)
    at java.lang.Thread.dispatchUncaughtException(Thread.java:1950)